update zenodo file
alpaka-group/llama pull request #121
Opened 2020-11-09 15:51 UTC by psychocoderHPC

- add contributor section
- fix indentions

2020-11-09 16:03 UTC, bernhardmgruber approved these changes

2020-11-10 07:38 UTC, psychocoderHPC commented
@theZiz, @MarkusVelten, @bertwesarg, @tdd11235813 please check your entry, e.g. affiliation during the contribution.

2020-11-10 09:29 UTC, MarkusVelten reviewed
Please add my affiliation as suggested.

2020-11-10 09:29 UTC, MarkusVelten commented on .zenodo.json
> +         "name":"Velten, Markus"
Thank you for the information, please add my affiliation:

```suggestion
         "name":"Velten, Markus",
         "affiliation":"TU Dresden"
```

2020-11-10 09:37 UTC, bernhardmgruber commented on .zenodo.json
> +         "name":"Gruber, Bernhard Manfred"
Please add my orcid as well! Thx!

```suggestion
         "name":"Gruber, Bernhard Manfred",
         "orcid":"0000-0001-7848-1690"
```

2020-11-17 10:58 UTC, psychocoderHPC commented
updated

2020-11-17 11:03 UTC, bernhardmgruber requested changes

2020-11-17 11:03 UTC, bernhardmgruber commented on .zenodo.json
> +	 "orcid":"0000-0001-7848-1690"
Please fix the whitespace here

2020-11-17 11:03 UTC, bernhardmgruber commented on .zenodo.json
> +	 "affiliation":"TU Dresden"
Please fix the whitespace here

2020-11-17 11:45 UTC, bernhardmgruber approved these changes

2020-11-17 11:46 UTC, merged